CREATE TABLE [dbo].[ButlerContractsOLD] (
    [fldContractID]                         INT           NOT NULL,
    [fldContractFName]                      NVARCHAR (50) NOT NULL,
    [fldContractLName]                      NVARCHAR (50) NOT NULL,
    [fldContractEmail]                      NVARCHAR (50) NOT NULL,
    [fldContractPhone]                      NVARCHAR (50) NOT NULL,
    [fldContractCreatedDate]                DATE          NOT NULL,
    [fldContractAddress1]                   NVARCHAR (50) NOT NULL,
    [fldContractAddress2]                   NVARCHAR (50) NOT NULL,
    [fldContractCity]                       NVARCHAR (50) NOT NULL,
    [fldContractProvinceID]                 TINYINT       NOT NULL,
    [fldContractCountryID]                  TINYINT       NOT NULL,
    [fldContractBirthDate]                  NVARCHAR (50) NOT NULL,
    [fldContracEmployer]                    NVARCHAR (50) NOT NULL,
    [fldContractEmployerContactName]        NVARCHAR (50) NOT NULL,
    [fldContractEmployerContactPhone]       NVARCHAR (50) NOT NULL,
    [fldContractEmployerTerm]               NVARCHAR (50) NOT NULL,
    [fldContractEmployerTermUnit]           NVARCHAR (50) NOT NULL,
    [fldContractMake]                       NVARCHAR (50) NOT NULL,
    [fldContractModel]                      NVARCHAR (50) NOT NULL,
    [fldContractYear]                       SMALLINT      NOT NULL,
    [fldContractTrim]                       NVARCHAR (50) NOT NULL,
    [fldContractSerialNumber]               NVARCHAR (1)  NULL,
    [fldContractLastUpated]                 NVARCHAR (50) NOT NULL,
    [fldContractStatusID]                   TINYINT       NOT NULL,
    [fldContractSalesRepID]                 NVARCHAR (50) NOT NULL,
    [fldContractContractDealerID]           TINYINT       NOT NULL,
    [fldProductID]                          TINYINT       NOT NULL,
    [fldContractOdometer]                   INT           NOT NULL,
    [fldContractEngineSize]                 NVARCHAR (50) NOT NULL,
    [fldContractLienHolder]                 NVARCHAR (50) NOT NULL,
    [fldContractInServiceDate]              NVARCHAR (50) NOT NULL,
    [fldContractPurchaseDate]               NVARCHAR (50) NOT NULL,
    [fldContractPostalCode]                 NVARCHAR (50) NOT NULL,
    [fldContractTermDetailsID]              INT           NOT NULL,
    [fldContractVIN]                        NVARCHAR (50) NOT NULL,
    [fldContractPurchasePrice]              FLOAT (53)    NOT NULL,
    [fldContractOldID]                      NVARCHAR (50) NOT NULL,
    [fldContractSalesPerson]                NVARCHAR (1)  NULL,
    [fldContractFactoryWarranty]            TINYINT       NOT NULL,
    [fldContractTypeOfFinanceID]            TINYINT       NOT NULL,
    [fldContractVehicleDescription]         NVARCHAR (50) NOT NULL,
    [fldContractEffectiveDate]              DATETIME2 (7) NOT NULL,
    [fldContractSellingPrice]               INT           NOT NULL,
    [fldContractTireSize]                   NVARCHAR (50) NOT NULL,
    [fldContractTireMake]                   NVARCHAR (1)  NULL,
    [fldContractStockNumber]                NVARCHAR (50) NOT NULL,
    [fldContractVehicleUsageID]             TINYINT       NOT NULL,
    [fldContractVehicleAgeID]               TINYINT       NOT NULL,
    [fldContractDeliveryDate]               NVARCHAR (50) NOT NULL,
    [fldContractTransactionTypeID]          TINYINT       NOT NULL,
    [fldContractElectricID]                 NVARCHAR (50) NOT NULL,
    [fldContractFuelTypeID]                 NVARCHAR (50) NOT NULL,
    [fldContractDriveTrainID]               NVARCHAR (50) NOT NULL,
    [fldContractFactoryWarrantyCancelled]   TINYINT       NOT NULL,
    [fldContractCompletedDate]              NVARCHAR (50) NOT NULL,
    [fldContractFinanceTerm]                NVARCHAR (50) NOT NULL,
    [fldContractPaymentAmount]              NVARCHAR (50) NOT NULL,
    [fldContractPaymentFrequencyID]         NVARCHAR (50) NOT NULL,
    [fldContractTransmissionID]             NVARCHAR (50) NOT NULL,
    [fldContractNegativeEquityAmount]       NVARCHAR (50) NOT NULL,
    [fldContractInterestRate]               FLOAT (53)    NOT NULL,
    [fldContractTotalFinanceAmount]         NVARCHAR (50) NOT NULL,
    [fldContractTradeInAllowance]           NVARCHAR (50) NOT NULL,
    [fldContractPayoutLienTradeIn]          NVARCHAR (50) NOT NULL,
    [fldContractDeposit]                    NVARCHAR (50) NOT NULL,
    [fldContractGapUnitTypeID]              NVARCHAR (50) NOT NULL,
    [fldContractVoidReason]                 NVARCHAR (50) NOT NULL,
    [fldContractOLDContractNumber]          NVARCHAR (50) NOT NULL,
    [fldContractCorrosionProtectionTypeNAS] NVARCHAR (50) NOT NULL,
    [fldContractLatitude]                   NVARCHAR (50) NOT NULL,
    [fldContractLongitude]                  NVARCHAR (50) NOT NULL,
    [fldContractTaxExempt]                  NVARCHAR (50) NOT NULL,
    [fldContractRemittance]                 NVARCHAR (50) NOT NULL,
    [fldContractSaleID]                     TINYINT       NOT NULL,
    [fldContractLienHolderAddress]          NVARCHAR (50) NOT NULL,
    [fldContractLienHolderCity]             NVARCHAR (50) NOT NULL,
    [fldContractLienHolderProvinceID]       TINYINT       NOT NULL,
    [fldContractLienCountryID]              NVARCHAR (50) NOT NULL,
    [fldContractLienPhone]                  NVARCHAR (50) NOT NULL,
    [fldContractLienHolderPostalCode]       NVARCHAR (50) NOT NULL,
    [fldContractFirstNationExempt]          BIT           NOT NULL,
    [fldContractFirstNationExemptID]        NVARCHAR (50) NOT NULL,
    [fldContractPaid]                       TINYINT       NOT NULL,
    [fldContractDownPayment]                INT           NOT NULL,
    [fldContractLoanAmount]                 FLOAT (53)    NOT NULL,
    [fldContractDownPaymentProtection]      BIT           NOT NULL,
    [fldContractMonths]                     TINYINT       NOT NULL,
    [fldContractMileage]                    TINYINT       NOT NULL,
    [fldContractPST]                        FLOAT (53)    NOT NULL,
    [fldContractMinimumPremium]             FLOAT (53)    NOT NULL,
    [fldContractCreatedBy]                  INT           NOT NULL,
    [fldContractGAPAmortizationTerm]        TINYINT       NOT NULL,
    [fldContractGAPPolicyPeriod]            TINYINT       NOT NULL
);


GO

