CREATE TABLE [postgres].[applications] (
    [id]                          INT            NOT NULL,
    [creator_id]                  BIGINT         NULL,
    [client_id]                   BIGINT         NULL,
    [vehicle_id]                  BIGINT         NULL,
    [template_id]                 BIGINT         NULL,
    [client_first_name]           VARCHAR (32)   NULL,
    [client_last_name]            VARCHAR (32)   NULL,
    [client_email]                VARCHAR (64)   NULL,
    [client_location]             NVARCHAR (255) NULL,
    [client_phone]                VARCHAR (16)   NULL,
    [vehicle_odometer]            BIGINT         NOT NULL,
    [vehicle_vin]                 VARCHAR (18)   NULL,
    [vehicle_type]                VARCHAR (255)  NULL,
    [vehicle_brand]               VARCHAR (255)  NULL,
    [vehicle_model]               VARCHAR (255)  NULL,
    [vehicle_series]              VARCHAR (255)  NULL,
    [vehicle_year]                BIGINT         NOT NULL,
    [vehicle_specifics]           NVARCHAR (255) NULL,
    [vehicle_additional]          NVARCHAR (255) NULL,
    [product_type]                VARCHAR (255)  NULL,
    [template_name]               TEXT           NOT NULL,
    [note]                        TEXT           NULL,
    [created_at]                  DATETIME       NULL,
    [updated_at]                  DATETIME       NULL,
    [is_paid]                     BIT            NOT NULL,
    [status]                      TEXT           NOT NULL,
    [deleted_at]                  DATETIME       NULL,
    [vehicle_is_used]             BIT            NULL,
    [generated_id]                TEXT           NULL,
    [dealership_id]               BIGINT         NULL,
    [vehicle_lien_holder]         TEXT           NULL,
    [template_insurance]          TEXT           NULL,
    [delete_comment]              TEXT           NULL,
    [client_first_nation_excempt] VARCHAR (16)   NULL,
    [dealership_name]             TEXT           NULL,
    [dealership_location]         NVARCHAR (255) NULL,
    [dealership_phone]            VARCHAR (16)   NULL,
    [published_at]                DATETIME       NULL,
    [cheque_number]               VARCHAR (255)  NULL,
    [paid_at]                     DATETIME       NULL
);


GO

